add rating components , moviecard , styling
azmat239/tmdb pull request #10
Opened 2023-10-04 15:57 UTC by azmat239

2023-10-05 05:58 UTC, auqibyousuf approved these changes

2023-10-05 13:48 UTC, UmmarHamid requested changes
Look good 
Small feedack

2023-10-05 13:48 UTC, UmmarHamid commented on app/components/Rating/Rating.tsx
> +    "w-10 bg-lightBlack rounded-full h-10 text-white text-center p-2 text-sm font-bold absolute top-[200px] left-8 border-2":
the absolute styles should not be added in the component like this, instead you should pass these as extraClasses.
Reason: This component might be used somewhere else where this posirion is not required

2023-10-05 13:48 UTC, UmmarHamid commented on app/components/Rating/Rating.stories.ts
> +export const Rating_Card: Story = {
```suggestion
export const Movie_Rating: Story = {
```

2023-10-05 13:48 UTC, UmmarHamid commented on app/components/MenuPopover/MenuPopover.tsx
> +        </Popover.Close>
This is  probably not required as clicking outside should close the menu

2023-10-05 13:48 UTC, UmmarHamid commented on app/components/MovieCard/MovieCard.tsx
> +        extraClasses="absolute top-2 left-36"
```suggestion
        extraClasses="absolute top-2 right-[someValue]"
```

2023-10-06 04:41 UTC, UmmarHamid approved these changes

2023-10-06 05:18 UTC, merged