Header component
azmat239/tmdb pull request #7
Opened 2023-09-27 08:46 UTC by azmat239

2023-09-27 09:43 UTC, UmmarHamid requested changes

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Logo/Logo.tsx
> +    </div>
Can we wrap this Image within a link component so that when user clicks on it they will be navigated to homepage

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Logo/Logo.tsx
> +      <Image src={logoImg} alt="no" width={150} height={150} />
'logoImg' should be a prop instead

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Menu/NavLink.tsx
> +};
The top element should just be the Link one and it will have classname similar to text component

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Menu/MenuNav.tsx
> +    </div>
the menu should be a ul element instead of div.
We don't want static 4 links in the menu, instead it should accept an array of links as prop and then use map function to render the links.
Kindly check the ticket description properly

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Menu/MenuNav.stories.ts
> +    url: "/",
here links array should be passed and those would be rendered by the menu

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Logo/logo.stories.ts
> +export const Logo_i: Story = {
Can we add a proper name here instead of Logo_i

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +    <div className="flex justify-evenly  bg-darkBlue py-4">
use header tag instead of div

2023-09-27 09:43 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +};
Header should take props for logo , menu and icon details

2023-09-27 10:19 UTC, azmat239 commented on app/components/Header/Menu/MenuNav.stories.ts
> +    url: "/",
didnt know how to do that

2023-09-28 03:26 UTC, UmmarHamid requested changes

2023-09-28 03:26 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +        <Logo ImgSrc={imgsrc} url="/" altText="image Not found" />
url and altText should be added from props.
You can pass a single logo prop which is an object like logo :{
imgSrc: '...',
imgAlt:'....',
url:'....'
}

2023-09-28 03:26 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +const Header = ({ imgsrc, links, actionIcon }: any) => {
define proper types for the header component

2023-09-28 03:26 UTC, UmmarHamid commented on app/components/Header/Menu/MenuNav.tsx
> +export default MenuNav;
This should have specific name like NavbarMenu

2023-09-28 03:26 UTC, UmmarHamid commented on app/components/Header/Menu/MenuNav.tsx
> +
You can define a single type for menu and kindly add it to its own file i.e Menu.types.ts

2023-09-28 03:26 UTC, UmmarHamid commented on app/components/Header/Menu/MenuNav.tsx
> +          </li>
This should show a linting error right?

2023-09-28 03:26 UTC, UmmarHamid commented on app/components/Header/Menu/NavLink.tsx
> +    <Link href={url} className={`${extraClasses}`}>
we can add conditional extraClasses

2023-09-28 08:40 UTC, UmmarHamid requested changes
@azmat239 Let me know if you need further assistance

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +        <BiSearchAlt2 className={actionIcon} />
This should also come from props

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavbarMenu/NavbarMenu.tsx
> +const MenuNav = ({ links, extraClasses }: MenutypeMain) => {
You can rename to Match the filename later

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Logo/Logo.type.ts
> +  logo: { ImgSrc: string; url: string; altText: string };
try to use camel case , So imgSrc instead of ImgSrc

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.types.ts
> +  links: Array<{ text: string; url: string }>;
```suggestion
  links: Array<NavLinkTypes>;
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.types.ts
> +  logo: { ImgSrc: string; url: string; altText: string };
```suggestion
  logo: LogoType;
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.stories.ts
> +      ImgSrc: "https://placehold.jp/150x20.png",
```suggestion
      imgSrc: "https://placehold.jp/150x20.png",
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +  let HeaderClass = classNames("text-2xl text-lightBlue");
is text-2xl required?

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +        <Logo logo={logo} />
Logo has a logo prop, it doesn't sound right.
You can name the as props or something

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavbarMenu/NavbarMenu.types.ts
> +};
```suggestion
export type NavbarMenutype= {
  links: Array<NavLinksTypes>;
  extraClasses?: string;
};
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavLink/NavLink.types.ts
> +export type NavLinkTypes = {
```suggestion
export type NavLinkType = {
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Logo/Logo.tsx
> +
```suggestion
const Logo = ({ imgSrc,url, altText, extraClasses }: LogoType) => {
  let logoClass = classNames("p-2");
  return (
    <Link href={url} className={`${logoClass} ${extraClasses ?? ""}`}>
      <Image src={imgSrc} alt={altText} width={150} height={20} />
    </Link>
  );
};

```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Logo/Logo.type.ts
> +};
```suggestion
export type LogoType = {
  imgSrc: string; 
  url: string;
   altText: string ;
  extraClasses?: string;
};
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavLink/NavLink.tsx
> +import { NavLinkTypes } from "./NavLink.types";
```suggestion
import { NavLinkType } from "./NavLink.types";
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavLink/NavLink.tsx
> +const NavLink = ({ text, url, extraClasses }: NavLinkTypes) => {
```suggestion
const NavLink = ({ text, url, extraClasses }: NavLinkType) => {
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavLink/NavLink.stories.ts
> +export const Navbar_Links: Story = {
```suggestion
export const Navbar_Link: Story = {
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavbarMenu/NavbarMenu.tsx
> +import { MenutypeMain } from "./NavbarMenu.types";
```suggestion
import { navbarMenuType } from "./NavbarMenu.types";
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavbarMenu/NavbarMenu.tsx
> +const MenuNav = ({ links, extraClasses }: MenutypeMain) => {
```suggestion
const MenuNav = ({ links, extraClasses }: navbarMenuType) => {
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/NavbarMenu/NavbarMenu.tsx
> +  let MenuNavClasses = classNames("flex mr-24");
```suggestion
  let menuNavClasses = classNames("flex gap-4 px-4");
```

2023-09-28 08:40 UTC, UmmarHamid commented on app/components/Header/Header.tsx
> +export default Header;
```suggestion
const Header = ({ logo, links, ActionIcon, extraClasses }: HeaderType) => {
  let headerClasses = classNames("flex justify-between bg-darkBlue py-4");
  return (
    <header className={`${headerClasses} ${extraClasses ?? ""}`}>
      <div className="flex gap-4">
        <Logo logo={logo} />
        <NavbarMenu links={links} />
      </div>
      <button>
        <ActionIcon  />
      </button>
    </header>
  );
};

export default Header;
```

2023-09-28 11:48 UTC, UmmarHamid approved these changes

2023-09-28 12:11 UTC, merged